name: null
favicon: null
layout_spectrum: 0.9835090099368244
typography_spectrum: 0.14063798426650465
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.14811474573798478
  lightness: 0.7458851633127779
  saturation: 0.7300578681752086
  rhythmicContrast: 0.1987616471014917
purpose: []
